### PR TITLE
Disable C++ exception handling for windows builds

### PR DESCRIPTION
**Pull request by kendalharland**
This should fix an error in the windows CI builds:

```
MSBuild version 17.9.8+b34f75857 for .NET Framework
2024-03-29T16:16:13.8972368Z 
2024-03-29T16:16:14.1874711Z   1>Checking Build System
2024-03-29T16:16:14.3859793Z   Building Custom Rule D:/a/firebase-cpp-sdk/firebase-cpp-sdk/BinaryCache/firebase/external/src/flatbuffers/CMakeLists.txt
2024-03-29T16:16:14.5018507Z   idl_parser.cpp
2024-03-29T16:16:15.3000069Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\vector(1041,13): error C2220: the following warning is treated as an error [D:\a\firebase-cpp-sdk\firebase-cpp-sdk\BinaryCache\firebase\external\src\flatbuffers-build\flatbuffers.vcxproj]
2024-03-29T16:16:15.3018139Z   (compiling source file '../flatbuffers/src/idl_parser.cpp')
2024-03-29T16:16:15.3018873Z   
2024-03-29T16:16:15.3405081Z C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\vector(1041,13): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [D:\a\firebase-cpp-sdk\firebase-cpp-sdk\BinaryCache\firebase\external\src\flatbuffers-build\flatbuffers.vcxproj]
```

### CODE REVIEW

**Review by compnerd — COMMENTED** [review]
Hmm, I wonder if this is going to cause some trouble. We do not enable exceptions when importing into Swift, and so this can cause ABI differences here. I think that we should disable exceptions: `/EHsc-` and then tell the C++ runtime to sod off (there is a macro for disabling exceptions).

**Comment by compnerd** [comment]
`/D_HAS_EXCEPTIONS=0` should do the trick for that.

**Comment by kendalharland** [comment]
Updated to disable exception handling. Thanks for the flag.

**Review by compnerd — APPROVED** [review]
If it builds, LGTM!

**Comment by hjyamauchi** [comment]
I'm curious why this wasn't an issue before. LGTM.

**Comment by compnerd** [comment]
Likely due to bad build system setup by Google, I suspect that they are modifying `CMAKE_C[XX]_FLAGS` manually which is not permitted, and that would silence the issue previously.

**Pull request merged**
